version: '3'
services:
  api-gateway:
    container_name: api
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - auth
    volumes:      
      - /api/node_modules
      - ./api-gateway:/api

  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  auth:
    container_name: auth
    build:
      context: auth
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:      
      - /auth/node_modules
      - ./auth:/auth
  
  product:
    container_name: product
    build:
      context: product
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - auth
    volumes:      
      - /product/node_modules
      - ./product:/product
    

volumes:
  mongo_data:

